name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # cache dependencies

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Install development dependencies which includes pytest, ruff, and production dependencies
        pip install -r requirements-dev.txt

    - name: Lint Code with Ruff
      run: |
        ruff check .

    - name: Run Pytest Suite
      run: |
        pytest
